---
# comments

num_of_classes: 13

model_path: ''
model_directory: '/home/joking/PycharmProjects/Chess_Recognition/models/'



data_directory: '/home/joking/PycharmProjects/Chess_Recognition/testing_images'
result_directory: '/home/joking/PycharmProjects/Chess_Recognition/'

default: InceptionResnetV2

MobileNetV2:
  model_name: "MobileNetV2"
  img_size: 224

NASNetMobile:
  model_name: 'NASNetMobile'
  img_size: 224

InceptionResNetV2:
  model_name: 'InceptionResNetV2'
  img_size: 150

Xception:
  model_name: 'Xception'
  img_shape: 299

