from pathlib import Path

import cv2
import lightning as L
from torch.utils.data import DataLoader, Dataset

from .transforms import orientation_train_transforms, orientation_val_transforms

# Rotation in degrees needed to bring the board to canonical form (white at bottom)
ORIENTATIONS = ["0", "90", "180", "270"]
ORIENTATION_TO_IDX = {o: i for i, o in enumerate(ORIENTATIONS)}


class OrientationDataset(Dataset):
    """Loads board images from a directory tree of the form:
        root/
          0/    90/    180/    270/
            *.jpg  *.png  ...

    Each subdirectory name is the rotation applied to reach canonical orientation,
    i.e. a board needing 180° rotation to place white at the bottom lives in '180/'.
    Generated by prepare_chessred.py which saves 4 rotated versions of each board.
    """

    def __init__(self, root: Path | str, transform=None):
        self.transform = transform
        self.samples: list[tuple[Path, int]] = []

        root = Path(root)
        if not root.exists():
            return
        for orientation_dir in sorted(root.iterdir()):
            if not orientation_dir.is_dir():
                continue
            label = ORIENTATION_TO_IDX.get(orientation_dir.name)
            if label is None:
                continue
            for ext in ("*.jpg", "*.jpeg", "*.png"):
                self.samples.extend((p, label) for p in orientation_dir.glob(ext))

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int):
        path, label = self.samples[idx]
        img = cv2.imread(str(path))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        if self.transform:
            img = self.transform(image=img)["image"]
        return img, label


class OrientationDataModule(L.LightningDataModule):
    """LightningDataModule for board orientation classification.

    Expects data prepared by training/prepare_chessred.py.
    Directory layout:
        data_dir/
          train/{0,90,180,270}/*.jpg
          val/{0,90,180,270}/*.jpg
          test/{0,90,180,270}/*.jpg
    """

    def __init__(
        self,
        data_dir: str,
        img_size: int = 224,
        batch_size: int = 64,
        num_workers: int = 4,
    ):
        super().__init__()
        self.save_hyperparameters()

    def setup(self, stage: str | None = None):
        hp = self.hparams
        root = Path(hp.data_dir)
        self.train_ds = OrientationDataset(root / "train", orientation_train_transforms(hp.img_size))
        self.val_ds = OrientationDataset(root / "val", orientation_val_transforms(hp.img_size))
        test_root = root / "test"
        self.test_ds = OrientationDataset(test_root, orientation_val_transforms(hp.img_size)) if test_root.exists() else None

    def train_dataloader(self):
        return DataLoader(
            self.train_ds,
            batch_size=self.hparams.batch_size,
            shuffle=True,
            num_workers=self.hparams.num_workers,
            pin_memory=True,
            drop_last=True,
        )

    def val_dataloader(self):
        return DataLoader(
            self.val_ds,
            batch_size=self.hparams.batch_size,
            shuffle=False,
            num_workers=self.hparams.num_workers,
            pin_memory=True,
        )

    def test_dataloader(self):
        if self.test_ds is None:
            return None
        return DataLoader(
            self.test_ds,
            batch_size=self.hparams.batch_size,
            shuffle=False,
            num_workers=self.hparams.num_workers,
        )
